name: Build & Deploy to Yandex Object Storage

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
      YC_S3_ENDPOINT: ${{ vars.YC_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build & Export static
        run: npm run build

      # awscli уже предустановлен на runner'ах. Ничего ставить не нужно.

      - name: Upload static assets (immutable)
        run: |
          aws s3 sync ./out "s3://${AWS_S3_BUCKET}/" \
            --endpoint-url "${YC_S3_ENDPOINT}" \
            --exclude "*.html" \
            --cache-control "public, max-age=31536000, immutable" \
            --acl public-read \
            --delete

      - name: Upload HTML (no-cache)
        run: |
          aws s3 sync ./out "s3://${AWS_S3_BUCKET}/" \
            --endpoint-url "${YC_S3_ENDPOINT}" \
            --exclude "*" \
            --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --acl public-read
