name: Build & Deploy to Yandex Object Storage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # >>> ВАЖНО: новый бакет под кириллический домен
  BUCKET: xn--b1apadobbw.xn--p1ai
  ENDPOINT: https://storage.yandexcloud.net
  AWS_DEFAULT_REGION: ru-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build & Export static
        run: |
          npm run build
          npm run export    # экспорт в папку out/

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_ACCESS_KEY }}
        run: aws sts get-caller-identity || true

      # ---------- ЗАГРУЗКА ----------
      # 1) Всё НЕ-HTML кладём с долгим кэшем (immutable)
      - name: Upload static assets (immutable)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./out s3://$BUCKET             --recursive             --exclude "*.html"             --cache-control "public, max-age=31536000, immutable"             --endpoint-url "$ENDPOINT"

      # 2) Все HTML — без кэша, чтобы обновления виделись сразу
      - name: Upload HTML (no-cache)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./out s3://$BUCKET             --recursive             --exclude "*"             --include "*.html"             --cache-control "no-cache, no-store, must-revalidate"             --content-type "text/html; charset=utf-8"             --endpoint-url "$ENDPOINT"